import React from 'react';
import {
  Bike,
  BookOpen,
  Bookmark,
  Camera,
  Car,
  Clapperboard,
  Code2,
  Coffee,
  Compass,
  Cpu,
  Dice5,
  Dumbbell,
  Film,
  Folder,
  Gamepad2,
  Gift,
  Globe2,
  Headphones,
  Heart,
  Laptop2,
  Mountain,
  Music2,
  Palette,
  PenSquare,
  Plane,
  Podcast,
  Radio,
  Rocket,
  Shield,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Star,
  Trophy,
  Tv,
  UtensilsCrossed
} from 'lucide-react';

type IconComponent = React.ComponentType<{ size?: string | number; className?: string }>;

const ICON_MAP: Record<string, IconComponent> = {
  film: Film,
  tv: Tv,
  gamepad: Gamepad2,
  book: BookOpen,
  music: Music2,
  headphones: Headphones,
  clapperboard: Clapperboard,
  radio: Radio,
  podcast: Podcast,
  camera: Camera,
  palette: Palette,
  pen: PenSquare,
  code: Code2,
  cpu: Cpu,
  smartphone: Smartphone,
  laptop: Laptop2,
  globe: Globe2,
  compass: Compass,
  mountain: Mountain,
  plane: Plane,
  car: Car,
  bike: Bike,
  dumbbell: Dumbbell,
  heart: Heart,
  sparkles: Sparkles,
  star: Star,
  rocket: Rocket,
  shield: Shield,
  trophy: Trophy,
  coffee: Coffee,
  utensils: UtensilsCrossed,
  shopping: ShoppingBag,
  gift: Gift,
  folder: Folder,
  bookmark: Bookmark,
  dice: Dice5
};

export const TAG_ICON_OPTIONS = [
  { value: '', label: '无图标' },
  { value: 'film', label: '电影' },
  { value: 'tv', label: '剧集' },
  { value: 'gamepad', label: '游戏' },
  { value: 'book', label: '书籍' },
  { value: 'music', label: '音乐' },
  { value: 'headphones', label: '耳机' },
  { value: 'clapperboard', label: '拍板' },
  { value: 'radio', label: '电台' },
  { value: 'podcast', label: '播客' },
  { value: 'camera', label: '摄影' },
  { value: 'palette', label: '绘画' },
  { value: 'pen', label: '写作' },
  { value: 'code', label: '编程' },
  { value: 'cpu', label: '芯片' },
  { value: 'smartphone', label: '手机' },
  { value: 'laptop', label: '电脑' },
  { value: 'globe', label: '全球' },
  { value: 'compass', label: '探索' },
  { value: 'mountain', label: '户外' },
  { value: 'plane', label: '旅行' },
  { value: 'car', label: '汽车' },
  { value: 'bike', label: '骑行' },
  { value: 'dumbbell', label: '健身' },
  { value: 'heart', label: '生活' },
  { value: 'sparkles', label: '精选' },
  { value: 'star', label: '收藏' },
  { value: 'rocket', label: '科幻' },
  { value: 'shield', label: '策略' },
  { value: 'trophy', label: '竞技' },
  { value: 'coffee', label: '日常' },
  { value: 'utensils', label: '美食' },
  { value: 'shopping', label: '购物' },
  { value: 'gift', label: '礼物' },
  { value: 'folder', label: '归档' },
  { value: 'bookmark', label: '标记' },
  { value: 'dice', label: '随机' }
];

export const getTagIcon = (icon?: string, className = 'w-4 h-4') => {
  if (!icon) return null;
  const Icon = ICON_MAP[icon];
  if (!Icon) return null;
  return <Icon className={className} />;
};
